sonar.projectKey=ncs-serial-modem-host-applications
sonar.organization=nrfconnect
sonar.host.url=https://sonarcloud.io
sonar.sources=.
sonar.inclusions=applications/**/src/**/*.c,applications/**/src/**/*.h,lib/include/**/*.h
