# Copyright (c) 2026 Nordic Semiconductor
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause

manifest:
  self:
    path: project

  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect

  projects:
    - name: nrf
      remote: ncs
      repo-path: sdk-nrf
      revision: v3.4-branch
      import: true
    - name: serial-modem
      remote: ncs
      repo-path: ncs-serial-modem
      revision: e23c2bde08a83e8a2908f78ee19f2b2ff5c6e46e
      path: serial-modem
