#
# Copyright (c) 2026 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# Use devicetree partitions (see boards/nrf54l15_cpuapp_mcuboot_partitions.dtsi).
SB_CONFIG_PARTITION_MANAGER=n
SB_CONFIG_BOOTLOADER_MCUBOOT=y
SB_CONFIG_MERGED_HEX_FILES=y
