#
# Copyright (c) 2026 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# Application identity
CONFIG_NCS_APPLICATION_BOOT_BANNER_STRING="Serial Modem Host 93m1 (AT)"

# Application modules
CONFIG_APP_NETWORK=y
CONFIG_APP_MODEM_AT=y
CONFIG_APP_CLOUD=y
CONFIG_APP_LOCATION=y
CONFIG_APP_BATTERY=y
CONFIG_APP_NETWORK_LOG_LEVEL_INF=y
CONFIG_APP_MODEM_AT_LOG_LEVEL_INF=y
CONFIG_APP_CLOUD_LOG_LEVEL_INF=y
CONFIG_APP_LOCATION_LOG_LEVEL_INF=y
CONFIG_APP_BATTERY_LOG_LEVEL_INF=y

# System / RTOS
CONFIG_NCS_SAMPLES_DEFAULTS=y
CONFIG_RESET_ON_FATAL_ERROR=n
CONFIG_MAIN_STACK_SIZE=8192
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096
CONFIG_ZBUS=y
CONFIG_ZBUS_MSG_SUBSCRIBER=y
CONFIG_SMF=y
CONFIG_SMF_ANCESTOR_SUPPORT=y
CONFIG_TASK_WDT=y

# Logging
CONFIG_LOG=y
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_LOG_BUFFER_SIZE=4096
CONFIG_MODEM_MODULES_LOG_LEVEL_INF=y

# Shell
CONFIG_SHELL=y
CONFIG_SHELL_STACK_SIZE=4096
CONFIG_SHELL_WILDCARD=n
CONFIG_SHELL_BACKEND_SERIAL_ASYNC_RX_BUFFER_SIZE=64

# Zephyr modem subsystem
CONFIG_MODEM_MODULES=y
CONFIG_MODEM_CHAT=y
CONFIG_MODEM_BACKEND_UART=y

# Board peripherals
CONFIG_GPIO=y
CONFIG_I2C=y

# Battery: nPM1300 fuel gauge + charger
CONFIG_SENSOR=y
CONFIG_MFD=y
CONFIG_NPM13XX_CHARGER=y
CONFIG_NRF_FUEL_GAUGE=y
CONFIG_NRF_FUEL_GAUGE_VARIANT_SECONDARY_CELL=y

# Power management
CONFIG_PM_DEVICE=y
