#
# Copyright (c) 2026 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

CONFIG_UART_INTERRUPT_DRIVEN=n
CONFIG_UART_ASYNC_API=y
CONFIG_MODEM_BACKEND_UART_ASYNC_HWFC=y

# Silence TF-M logs to avoid conflicts with modem UART.
CONFIG_TFM_LOG_LEVEL_SILENCE=y

CONFIG_MODEM_CMUX_MSC_FC_THRESHOLD=32
