#
# Copyright (c) 2026 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# Disable Partition Manager.
SB_CONFIG_PARTITION_MANAGER=n

# Enable MCUboot bootloader support.
SB_CONFIG_BOOTLOADER_MCUBOOT=y

# Add a merged hex file to the build output.
SB_CONFIG_MERGED_HEX_FILES=y
