name: Build

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

concurrency:
  group: build-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: self-hosted
    container: ghcr.io/zephyrproject-rtos/ci:v0.29.2
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    strategy:
      fail-fast: false
      matrix:
        include:
          - app: 91m1
            board: nrf54l15dk/nrf54l15/cpuapp/ns
          - app: 93m1
            board: nrf54l15dk/nrf54l15/cpuapp
    name: Build ${{ matrix.app }} (${{ matrix.board }})
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: serial-modem-host-applications

      - name: Initialize West workspace
        working-directory: serial-modem-host-applications
        run: |
          if [ ! -d "../.west" ]; then
            west init -l .
          else
            echo ".west folder already exists, skipping west init."
          fi
          west update -o=--depth=1 -n

      - name: Build application
        working-directory: serial-modem-host-applications/applications/${{ matrix.app }}
        run: west build -b ${{ matrix.board }} -p
